[project]
name = "sig-benchmarks"
version = "0.1.0"
requires-python = ">=3.12, <3.13"
dependencies = [
    "pyyaml>=6.0.3",
    "matplotlib>=3.9.4",
    "numpy",
    "fbm>=0.3.0",
    "tqdm",
]

[project.optional-dependencies]
chen-signatures = [
    "chen-signatures==0.2.4",
    "torch",
]
iisignature = [
    "iisignature",
    "numpy"
]
roughpy = [
    "RoughPy==0.3.0",
]
signature-rs = [
    "signature-py",
]
log-signatures-pytorch = [
    "torch>=2.9.1",
]
pathsig = [
    "cmake>=3.24",
    "ninja>=1.11",
    "pathsig==0.2.1",
    "scikit-build-core>=0.10",
    "torch>=2.4",
]
pysiglib = [
    "pysiglib[cuda]>=3.0.3",
]
stochastax = [
    "jax[cuda]",
    "stochastax",
]
polysigkernel = [
    "jax[cuda]",
    "polysigkernel",
]
all = [
    "chen-signatures==0.2.4",
    # "iisignature",
    "cmake>=3.24",
    "fbm>=0.3.0",
    "jax[cuda]",
    "ninja>=1.11",
    "pysiglib[cuda]>=3.0.3",
    "pathsig==0.2.1",
    "RoughPy==0.3.0",
    "scikit-build-core>=0.10",
    "signature-py",
    "stochastax",
    "signax",
    "keras_sig",
    "torch>=2.9.1",
]

[tool.uv.sources]
stochastax = { git = "https://github.com/luke-a-thompson/Stochastax.git", rev = "09c9612e9352bb05a0a92a30e2bc391cdd2c78e1" }
keras_sig = { git = "https://github.com/remigenet/keras_sig.git", rev = "32367ad019ede3c31c2b6f3a1197090696d4a8eb" }
signax = { git = "https://github.com/anh-tong/signax", rev = "4961f361b60d293f4e7679dba028b93dead89c39" }
polysigkernel = { git = "https://github.com/luke-a-thompson/polysigkernel.git", rev = "807234d4ffc7e123cd3392b78e763c6a41269384" }
signature-py = { git = "https://github.com/ChosunOne/signature-rs.git", subdirectory = "signature-py", rev = "671b0fba16f1c542e76910c2825a9e8b185d3a93" }

[tool.uv.extra-build-dependencies]
iisignature = ["numpy"]

[tool.uv]
no-build-isolation-package = ["pathsig"]
