[project]
name = "sig-benchmarks"
version = "0.1.0"
requires-python = ">=3.12, <3.13"
dependencies = [
    "pyyaml>=6.0.3",
    "matplotlib>=3.9.4",
    "numpy",
    "tqdm",
]

[dependency-groups]
dev = [
    "pytest>=8.0",
]

[project.optional-dependencies]
chen-signatures = [
    "chen-signatures==0.2.4",
    "torch",
]
iisignature = [
    "iisignature",
    "numpy"
]
signature-rs = [
    "signature-py",
]
log-signatures-pytorch = [
    "torch>=2.9.1",
]
signatory = [
    "signatory",
    "torch>=2.9.1",
]
pathsig = [
    "cmake>=3.24",
    "ninja>=1.11",
    "pathsig==0.2.1",
    "scikit-build-core>=0.10",
    "torch>=2.4",
]
pysiglib = [
    "pysiglib[cuda]==4.0.0rc1",
    "torch>=2.9.1",
]
signax = [
    "jax[cuda]",
    "signax",
]
keras-sig = [
    "jax[cuda]",
    "keras_sig",
]
polysigkernel = [
    "jax[cuda]",
    "polysigkernel",
]
sigkerax = [
    "jax[cuda]",
]
sigkernel = [
    "sigkernel",
    "torch>=2.9.1",
]
tensordev = [
    "jax[cuda]",
    "tensordev==0.0.2",
]
all = [
    "chen-signatures==0.2.4",
    # "iisignature",
    "cmake>=3.24",
    "jax[cuda]",
    "ninja>=1.11",
    "pysiglib[cuda]==4.0.0rc1",
    "pathsig==0.2.1",
    "scikit-build-core>=0.10",
    "signature-py",
    "signax",
    "signatory",
    "sigkernel",
    "tensordev==0.0.2",
    "keras_sig",
    "torch>=2.9.1",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu130", marker = "sys_platform == 'win32'" },
]
pysiglib = { path = "../pySigLib" }
pysiglib-cuda = { path = "../pySigLib/plugins/cuda" }
keras_sig = { git = "https://github.com/remigenet/keras_sig.git", rev = "32367ad019ede3c31c2b6f3a1197090696d4a8eb" }
signax = { git = "https://github.com/anh-tong/signax", rev = "4961f361b60d293f4e7679dba028b93dead89c39" }
polysigkernel = { git = "https://github.com/luke-a-thompson/polysigkernel.git", rev = "807234d4ffc7e123cd3392b78e763c6a41269384" }
signatory = { git = "https://github.com/datasig-ac-uk/signatory.git", rev = "f263b9d9358c81a144c9d9bb78006745136abbf8" }
signature-py = { git = "https://github.com/ChosunOne/signature-rs.git", subdirectory = "signature-py", rev = "671b0fba16f1c542e76910c2825a9e8b185d3a93" }
sigkernel = { git = "https://github.com/crispitagorico/sigkernel.git", rev = "40a583155ea8d2194af0e90dddab37e2659cfcfd" }

[tool.uv.extra-build-dependencies]
iisignature = ["numpy"]
signatory = [{ requirement = "torch", match-runtime = true }]
sigkernel = ["cython>=0.29"]

[tool.uv]
constraint-dependencies = ["pysiglib-cuda==4.0.0rc1", "numba==0.65.1"]
no-build-isolation-package = ["pathsig"]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true
